#!/bin/bash

set -e

if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "ERROR: you must execute this script from the OpenShift Git repository." 1>&2
  exit 1
fi

PR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
PR_NUMBER="$(gh pr list -H $PR_BRANCH --json number | jq -r '.[][]')"
PR_COUNT="$(gh pr list -H $PR_BRANCH -s open | wc -l)"
AUTHOR="$(gh pr view $PR_NUMBER --json author | jq -r '.[][]')"
BASE_REF="$(gh pr view $PR_NUMBER --json baseRefName | jq -r '.[]')"

if [ $PR_COUNT -gt 1 ]; then
  echo "ERROR: there are multiple PRs referencing your working branch." 1>&2
  exit 1
fi

generate_pr_data()
{
  cat <<EOF
    {
    "PR_BRANCH": "$PR_BRANCH",
    "BASE_REPO": "openshift/openshift-docs",
    "PR_NUMBER": "$PR_NUMBER",
    "USER_NAME": "$AUTHOR",
    "BASE_REF": "$BASE_REF",
    "REPO_NAME": "$AUTHOR/openshift-docs"
    }
EOF
}

curl -H 'Content-Type: application/json' --request POST --data "$(generate_pr_data)" https://eoa6vg2jiwjbnh6.m.pipedream.net